/*
 * <캐시홈트> 캐시적립 매크로
 * 
 * OS: 				Microsoft Windows 10
 * AndroidVersion: 	Android 7+
 * NoxVersion: 		6.6.0.1+
 * Display:			w=360 h=600 dpi=120
 * Setting:			Allways_Vertical_Screen(항상 세로화면으로 사용)
 */
#Include %A_Temp%\AutoHotKey\cashhomt-cash-obtainer\lib\Gdip.ahk ; https://autohotkey.com/board/topic/29449-gdi-standard-library-145-by-tic
#Include %A_Temp%\AutoHotKey\cashhomt-cash-obtainer\lib\Gdip_ImageSearch.ahk
#Include %A_Temp%\AutoHotKey\cashhomt-cash-obtainer\lib\Utils.ahk

#SingleInstance Force
#NoEnv

SetWorkingDir %A_ScriptDir%
SetBatchLines -1

; ------------------------------------- 컴파일 패키징 ---------------------------------------

; 배포 경로
global DISTRIBUTION_PATH := A_Temp . "\AutoHotKey\cashhomt-cash-obtainer\"

; 최초 실행 시, 패키지 배포에 대한 동의 여부를 받는다
isNotExist := FileExist(DISTRIBUTION_PATH . "cashhomt-macro.ini") = "" ? true : false
IniRead, agreement, % DISTRIBUTION_PATH . "cashhomt-macro.ini", DISTRIBUTION, consent ; , false
didNotAgree := agreement == "true" ? false : true

if (isNotExist || didNotAgree)
{
	; 동의 문구를 작성한다
	msg =
	(
The libraries must be distributed to the path below to run this program. Do you agree?
(If not, this program will be terminated.)
		
============ DISTRIBUTION PATH ============
%DISTRIBUTION_PATH%

=============== LIBRARIES ===============

	)
	packages := ["lib\Gdip.ahk", "lib\Gdip_ImageSearch.ahk", "lib\Utils.ahk", "img\btn_boost.bmp", "img\ghost.bmp", "img\btn_go_page.bmp", "img\ico_cashhomet.bmp", "img\btn_failed.bmp", "img\finish.bmp"]
	for k, v in packages
	{
		;~ msg .= A_Temp "\AutoHotKey\" v "`n"
		msg .= ".\" . v . "`n"
	}
	
	; 라이브러리 배포에 동의하지 않으면 프로그램을 종료한다
	MsgBox, % 4+48, % "Notice", % msg
	IfMsgBox, No
	{
		ExitApp
	}
	
	; 라이브러리 배포 동의서를 생성한다
	IfNotExist, % DISTRIBUTION_PATH
	{
		FileCreateDir, % DISTRIBUTION_PATH
	}
	IniWrite, true, % DISTRIBUTION_PATH . "cashhomt-macro.ini", DISTRIBUTION, consent
	FileSetAttrib, +H, % DISTRIBUTION_PATH . "cashhomt-macro.ini"
}

; 패키징한 라이브러리 및 이미지를 배포할 디렉터리를 생성한다
IfNotExist, % DISTRIBUTION_PATH . "lib\"
{
	FileCreateDir, % DISTRIBUTION_PATH . "lib\"
}
IfNotExist, % DISTRIBUTION_PATH . "img\"
{
	FileCreateDir, % DISTRIBUTION_PATH . "img\"
}
IfNotExist, % DISTRIBUTION_PATH . "log\"
{
	FileCreateDir, % DISTRIBUTION_PATH . "log\"
}

; 패키징한 라이브러리 및 이미지를 배포한다
FileInstall, ..\lib\Gdip.ahk, %DISTRIBUTION_PATH%\lib\Gdip.ahk, 0
FileInstall, ..\lib\Gdip_ImageSearch.ahk, %DISTRIBUTION_PATH%\lib\Gdip_ImageSearch.ahk, 0
FileInstall, ..\lib\Utils.ahk, %DISTRIBUTION_PATH%\lib\Utils.ahk, 0

FileInstall, ..\img\btn_boost.bmp, %DISTRIBUTION_PATH%\img\btn_boost.bmp, 0
FileInstall, ..\img\ghost.bmp, %DISTRIBUTION_PATH%\img\ghost.bmp, 0
FileInstall, ..\img\btn_go_page.bmp, %DISTRIBUTION_PATH%\img\btn_go_page.bmp, 0
FileInstall, ..\img\ico_cashhomet.bmp, %DISTRIBUTION_PATH%\img\ico_cashhomet.bmp, 0
FileInstall, ..\img\btn_failed.bmp, %DISTRIBUTION_PATH%\img\btn_failed.bmp, 0
FileInstall, ..\img\finish.bmp, %DISTRIBUTION_PATH%\img\finish.bmp, 0

; ------------------------------------------------------------------------------------------

; ------------------------------------------ GUI -------------------------------------------

; Generated by AutoGUI 2.6.2
Gui Add, GroupBox, x8 y2 w249 h97, Controller ;
Gui Add, Button, x24 y16 w57 h51 gStart, �� ; ▶
Gui Add, Text, x16 y72 w72 h16 +0x200, Start / Ctrl+[
Gui Add, Button, x104 y16 w56 h52 gStop, || 
Gui Add, Text, x96 y72 w72 h17 +0x200, Stop / Ctrl+]
Gui Add, Button, x184 y16 w56 h52 gExit, �� ; ■
Gui Add, Text, x176 y72 w70 h15 +0x200, Exit / Ctrl+\
Gui Add, GroupBox, x8 y104 w249 h49, Parameter
Gui Add, Edit, x24 y123 w160 h18 gNameReceiver vVarNm, name
Gui Add, Edit, x191 y123 w49 h18 gIndexReceiver vVarIdx, index

Gui Show, w265 h160, cashhomt-cash-obtainer
Return

; ------------------------------------------------------------------------------------------

; ---------------------------------------- 전역변수 ----------------------------------------

; Nox 인스턴스명
global appNm
; Nox 인스턴스 순서번호
global instIdx
; 광고 대기중인가?
global isWaiting
; 매크로를 정지했는가?
global isStopped
; 캐시적립 버튼 이미지
global IMG_CASH_GETTER := DISTRIBUTION_PATH . "img\btn_boost.bmp"
; 광고 대기화면 이미지
global IMG_WAITING_AD := DISTRIBUTION_PATH . "img\ghost.bmp"
; 캐시적립 페이지 이동 버튼 이미지
global IMG_GO_TO_GETTING_PAGE := DISTRIBUTION_PATH . "img\btn_go_page.bmp"
; 캐시홈트 홈 아이콘 이미지
global IMG_APP_ICON := DISTRIBUTION_PATH . "img\ico_cashhomet.bmp"
; 캐시적립 실패 확인 버튼 이미지
global IMG_FAILED_TO_GET := DISTRIBUTION_PATH . "img\btn_failed.bmp"
; 모든 캐시적립 완료 이미지
global IMG_FINISH := DISTRIBUTION_PATH . "img\finish.bmp"

; ------------------------------------------------------------------------------------------

; ------------------------------------------ 함수 ------------------------------------------

/*
 * 윈도우를 활성화하여 이전 페이지로 이동합니다.
 */
goBackActively()
{
	; 뒤로가기 버튼 좌표
	x := 390
	y := 530
	
	; 활성 뒤로가기 클릭
	WinActivate, %appNm%
	MouseClick, left, x, y
	
	return
}

/*
 * 윈도우를 활성화하지 않고 이전 페이지로 이동합니다.
 */
goBackInactively()
{
	; 비활성 뒤로가기 클릭
	ControlClick, X30 Y530, % convertToNoxIndex(instIdx), , , , NA
	
	; Esc 클릭 (미작동)
	/*
	PostMessage, 0x100, 27, 65537, , %appNm%
	PostMessage, 0x101, 27, 65537, , %appNm%
	ControlSend, , Send {Esc}, %appNm%
	*/
	
	return
}

/*
 * 순서번호를 NoxAppPlayer의 우측 메뉴의 컨트롤명으로 변환한다.
 * 
 * e.g. 0: nox, 1: Nox_1, 2: Nox_2, ...
 */
convertToNoxIndex(index)
{
	result := ""
	
	if (index <= 0)
	{
		result := "nox"
	}
	else
	{
		result := "Nox_" . index
	}
	
	return result
}

; ------------------------------------------------------------------------------------------

; ------------------------------------ 파라미터 초기화 -------------------------------------

NameReceiver:
	; GUI에서 Nox 인스턴스명을 받아온다
	Gui, Submit, NoHide	; <- GuiControlGet would work here too
	appNm := varNm
return

IndexReceiver:
	; GUI에서 Nox 인스턴스 순서 번호를 받아온다
	Gui, Submit, NoHide	; <- GuiControlGet would work here too
	instIdx := varIdx
return

; ------------------------------------------------------------------------------------------

; ------------------------------------- 캐시적립 실행 --------------------------------------

^[:: 	; 시작 단축키: Ctrl + [
Start: 	; 시작버튼

	; 파라미터를 변경할 수 없도록 GUI를 비활성화한다
	GuiControl, Disable, varNm
	GuiControl, Disable, varIdx
	
	; 전역변수를 초기화한다
	isWaiting := false
	isStopped := false
	
	; 녹스앱플레이어 윈도우 정보를 가져온다
	WinGet, noxWinHandle, ID, %appNm%
	
	loop
	{
		; 중지 버튼을 누르면 매크로를 종료한다
		if (isStopped)
		{
			break
		}
		
		; 1. `적립부스트 버튼`이 보이는가?
		canGet := Utils.searchImage(IMG_CASH_GETTER, noxWinHandle, x, y)

		if (canGet)
		{
			; 2. 적립버튼이 보이면 적립한다
			Utils.clickInactively(x, y, appNm)
		}
		else
		{
			; 3. `광고 대기화면`이 보이면 광고 대기중임을 설정한다
			if (Utils.searchImage(IMG_WAITING_AD, noxWinHandle, x, y))
			{
				isWaiting := true
			}
			
			; 4. `광고 대기화면`이 최초로 나타난 뒤, 사라지면 광고가 노출된 것으로 간주한다
			if (isWaiting)
			{
				; 4-1. 일정 시간마다 광고가 아직 대기중인지 확인한다
				while (Utils.searchImage(IMG_WAITING_AD, noxWinHandle, x, y))
				{
					sleep, 750
					
					; 중지 버튼을 누르면 매크로를 종료한다
					if (isStopped)
					{
						break, 2
					}
				}
				
				; 4-2. 광고화면이 완전히 로딩될 때까지 기다린다
				; (여러 디바이스가 동시에 광고화면을 종료하는 걸 막는다)
				Random, randomSec, 1500, 2000
				sleep, randomSec
				
				; 4-3. 광고화면을 종료한다
				goBackInactively()
				isWaiting := false
			}
			
			if (Utils.searchImage(IMG_GO_TO_GETTING_PAGE, noxWinHandle, x, y))
			{
				; 5. 메인페이지로 잘못 이동했으면 다시 `캐시적립화면`으로 이동한다
				Utils.clickInactively(x, y, appNm)
			}
			else if (Utils.searchImage(IMG_APP_ICON, noxWinHandle, x, y))
			{
				; 6. 캐시홈트 앱 밖으로 이동했으면 다시 앱을 실행한다
				Utils.clickInactively(x, y, appNm)
			}
			else if (Utils.searchImage(IMG_FAILED_TO_GET, noxWinHandle, x, y))
			{
				; 7. `캐시적립 실패화면`이 노출되면 다시 `캐시적립화면`으로 이동한다
				Utils.clickInactively(x, y, appNm)
			}
			else if (Utils.searchImage(IMG_FINISH, noxWinHandle, x, y))
			{
				; 8. `전체 캐시적립 성공화면`이 노출되면 프로그램 실행을 중지한다
				break
			}
		}
		
		; 캐시 적립간격은 0.2초로 한다
		sleep, 200
	}
	
	; 파라미터를 변경할 수 있도록 GUI를 활성화한다
	GuiControl, Enable, varNm
	GuiControl, Enable, varIdx
	
return

; ------------------------------------------------------------------------------------------

; ------------------------------------- 캐시적립 중지 --------------------------------------

^]:: 	; 중지 단축키: Ctrl + ]
Stop: 	; 중지버튼
	isStopped := true
return

; ------------------------------------------------------------------------------------------

; ------------------------------------- 프로그램 종료 --------------------------------------

^\:: 	; 종료 단축키: Ctrl + \
Exit: 	; 종료버튼
GuiEscape:
GuiClose:
	ExitApp
return

; ------------------------------------------------------------------------------------------
